---
name: Bundle-DBD-PO
version: 2.08
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: 'Bundle::DBD::PO - A bundle to install all DBD::PO related modules'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Simple: 0
requires:
  DBD::PO: 2.08
  DBI: 0
  perl: 5.006
recommends:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.34
provides:
  Bundle::DBD::PO:
    file: lib/Bundle/DBD/PO.pm
    version: 2.08
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
