---
name: Bundle-DBD-PO
version: 2.03
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: 'Bundle::DBD::PO - A bundle to install all DBD::PO related modules'
license: perl
resources:
  license: ~
requires:
  DBD::PO: 2.03
  DBI: 0
build_requires:
  Test::Simple: 0
recommends:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Bundle::DBD::PO:
    file: lib/Bundle/DBD/PO.pm
    version: 2.03
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
